{% set version = "0.4.4" %}

package:
  name: jupyter_server_terminals
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-server-terminals/jupyter_server_terminals-{{ version }}.tar.gz
  sha256: 57ab779797c25a7ba68e97bcfb5d7740f2b5e8a83b5e8102b10438041a7eac5d

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - hatchling >=1.5
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - terminado >=0.8.3
    # - pywinpty >=2.0.3  # rely on terminado to provide this

test:
  source_files:
    - tests
  imports:
    - jupyter_server_terminals
  commands:
    - pip check
    - pytest -vv --cov=jupyter_server_terminals --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=80
  requires:
    - jupyter_server >=2.0.0rc8
    - pip
    - pytest >=7.0
    - pytest-cov
    - pytest-jupyter-server >=0.5.3
    - pytest-timeout

about:
  home: https://github.com/jupyter-server/jupyter_server_terminals
  summary: A Jupyter Server Extension Providing Terminals.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/jupyter_server
